FROM ghcr.io/ggml-org/llama.cpp:server

ENV LLAMA_ARG_HOST=0.0.0.0
ENV LLAMA_ARG_PORT=10000
ENV LLAMA_ARG_MODEL_URL=https://huggingface.co/unsloth/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-Q4_K_M.gguf
ENV LLAMA_ARG_CTX_SIZE=4096
ENV LLAMA_ARG_N_PARALLEL=1
ENV LLAMA_ARG_N_PREDICT=512
ENV LLAMA_ARG_THREADS=-1
ENV LLAMA_ARG_THREADS_BATCH=-1
ENV LLAMA_ARG_TEMPERATURE=0.7

EXPOSE 10000
